name: Build

on:
  workflow_dispatch:
  push:
    tags: ['v*']

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: pip install pyinstaller PyQt5 mitmproxy requests
      - run: pyinstaller build.spec --noconfirm
      - uses: actions/upload-artifact@v4
        with:
          name: CryptoProxy-Windows
          path: dist/CryptoProxy/

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: pip install pyinstaller PyQt5 mitmproxy requests
      - run: pyinstaller build.spec --noconfirm
      - uses: actions/upload-artifact@v4
        with:
          name: CryptoProxy-macOS
          path: dist/CryptoProxy.app/
